# dev-role.yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: dev
  name: dev-role
rules:
- apiGroups: [""]
  resources: ["pods", "deployments", "replicasets"]
  verbs: ["get", "list", "create", "update", "delete"]
