# prod-role-binding.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prod-user-binding
  namespace: prod
subjects:
- kind: User
  name: prod-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: prod-role
  apiGroup: rbac.authorization.k8s.io
